### ISSUE TITLE
moving some code of index.js that belongs to redux into redux folder

### ISSUE THREAD

**Issue by abhay27chauhan** [gokulprathin8/Jaisalmer-E-Commerce#34]
**Is your feature request related to a problem? Please describe.**
i would suggest to move the code from line no. 11 to 22 into redux folder as it belongs to redux and so that index 

![Screenshot 2021-03-26 at 9 32 30 PM](https://user-images.githubusercontent.com/42849043/112659999-f905e700-8e7a-11eb-99b1-c0d29e565ecd.png)

**Describe the solution you'd like**
i will putting code into store.js file inside the redux folder

**Comment by abhay27chauhan** [comment]
I am a participant of GSSOC21, so please let me know if this is a valid proposal

**Comment by gokulprathin8** [comment]
Hi @abhay27chauhan, as of now - We are following Default Flux Architecture, for contributors to understand the redux integration better we have decided to have our reducers and persistors integrate into the store at index.js, which makes it easy to understand.

https://scotch.io/tutorials/getting-to-know-flux-the-react-js-architecture
