### ISSUE TITLE
Using NLP for detecting the customer review

### ISSUE THREAD

**Issue by ParthSingh0506** [gokulprathin8/Jaisalmer-E-Commerce#39]
**Describe the solution you'd like**

->The basic idea is that our ML model will able to understand the review of the customer and after that it will make output whether the review is bad or it is good

**Comment by ParthSingh0506** [comment]
@gokulprathin8  kindly assign me this issue

**Comment by gokulprathin8** [comment]
Hi @ParthSingh0506 , this issue is assigned to you.

**Comment by ParthSingh0506** [comment]
@gokulprathin8 Do I need to use the dataset from the dataset folder from ML folder of Jaisalmer Website or I have to collect the data and use for training . Can you also tell me that on what type of products you want review because based on the products I will collect the customer review for training model
.

**Comment by ParthSingh0506** [comment]
@gokulprathin8 I have created the PR kindly check it
