### ISSUE TITLE
Social Auth

### ISSUE THREAD

**Issue by hi-18-K** [gokulprathin8/Jaisalmer-E-Commerce#4]
Also we can connect social authentication with website for easy and less time consuming signup and login functionality implementation. I would like to work on this as GSSoC participant.

**Comment by gokulprathin8** [comment]
Hi, @hi-18-K ,

    This will be treated as the same feature, with the signup process, use Django's AllAuth library for reference. 

https://django-allauth.readthedocs.io/en/latest/providers.html
