### ISSUE TITLE
Custom User model Feature.

### ISSUE THREAD

**Issue by nikfzy** [gokulprathin8/Jaisalmer-E-Commerce#5]
A custom user model to override djnago's basic user model to support multiple custom user type roles and data which would be used for this application. With a Profile Model to Other secondary user information. The roles of user can be kept dynamic with each type of role or group of roles can later on be assigned to a group with already given permissions.

**Comment by gokulprathin8** [comment]
Hi @nikfzy ,

This issue is already raise here https://github.com/gokulprathin8/Jaisalmer-E-Commerce/issues/2
If you are interested, let me know @ https://github.com/gokulprathin8/Jaisalmer-E-Commerce/issues/2
