### ISSUE TITLE
QA : Add Formatter and Linter

### ISSUE THREAD

**Issue by Aryamanz29** [gokulprathin8/Jaisalmer-E-Commerce#62]
- Need a workflow that ensures every contributor should follow the [PEP-8](https://www.python.org/dev/peps/pep-0008/) style guide for python code.
- We can use `flake8` for linting and `Black` for formatting source code.
- Also this workflow runs on every PR which ensures the code follows  [PEP-8](https://www.python.org/dev/peps/pep-0008/) standard or not.

**Comment by Aryamanz29** [comment]
I would like to work on this @gokulprathin8  @saketh018

**Comment by harshakhmk** [comment]
Can I work on this too? @gokulprathin8

**Comment by Aryamanz29** [comment]
@gokulprathin8 At least do comments about this issue before closing .

Thanks

**Comment by gokulprathin8** [comment]
Hi @Aryamanz29,
   Most of the modern IDE's such as Pycharm come with Formatting Tools inbuilt.
   
   Reference: https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html

**Comment by Aryamanz29** [comment]
What about lint ? Does they follow `PEP8` standard also ?

**Comment by gokulprathin8** [comment]
@Aryamanz29 
As for Linter, I have already added pylint. Which will be pushed in my next commit along with some other changes including but not limited to Cart API modifications, API monitoring and logging.

Pylint was globally installed and hence didn't show up in any other commits (in requirements.txt). Which is fixed.

**Comment by gokulprathin8** [comment]
@Aryamanz29 ,

If you are interested in contributing, Please take a look at pending issues. I apologize for closing the issue without any notice.
